### ISSUE TITLE
当构造函数含address类型的参数时交易成功但部署无效

### ISSUE THREAD

**Issue by mianhuatan** [uhexio/sero-skit#1]
当合约构造函数含 address类型的参数时，交易发送成功后，通过 sero_getTransactionReceipt 无法获取合约地址，手动调用sero_getTransactionReceipt 发现status为0，合约部署未成功

**Comment by uhexio** [comment]
> 当合约构造函数含 address类型的参数时，交易发送成功后，通过 sero_getTransactionReceipt 无法获取合约地址，手动调用sero_getTransactionReceipt 发现status为0，合约部署未成功

address传入的是智能合约地址吗？

**Comment by mianhuatan** [comment]
传入的是用户的主收款码，比如uGAJXVoi33qwyUviBrc8de2UyjPFgqTagSTftALBYwdvYaAHooQvY528dqE58L4qRVs7EWM2tykhR3MagAmNP6iWEWNH93vBp2DnuXNvUR8Cn7D1fKrpDrbCjaPqgwhNdqN
同样的一份代码，只是构造函数的参数不同，如果传入address类型参数，合约不能正常部署

**Comment by uhexio** [comment]
> 当合约构造函数含 address类型的参数时，交易发送成功后，通过 sero_getTransactionReceipt 无法获取合约地址，手动调用sero_getTransactionReceipt 发现status为0，合约部署未成功

Hi，传入的Address是什么格式，请把Address值发出来看下。

**Comment by uhexio** [comment]
> 传入的是用户的主收款码，比如uGAJXVoi33qwyUviBrc8de2UyjPFgqTagSTftALBYwdvYaAHooQvY528dqE58L4qRVs7EWM2tykhR3MagAmNP6iWEWNH93vBp2DnuXNvUR8Cn7D1fKrpDrbCjaPqgwhNdqN
> 同样的一份代码，只是构造函数的参数不同，如果传入address类型参数，合约不能正常部署

OK，请把 web3 deploy的内容发一下，我测试下。

**Comment by mianhuatan** [comment]
试试这个能部署么
pragma solidity ^0.4.25;

contract test{
    address addr;
    constructor(address _addr) public {
        addr =_addr;
    }
     
    function setAdderss(address _addr) external  {
        addr =_addr;

    }
}

**Comment by uhexio** [comment]
```
pragma solidity ^0.4.25;

contract test{
address public addr;
constructor(address _addr) public {
addr =_addr;
}

function setAdderss(address _addr) external  {
    addr =_addr;

}
}
```

可以发布。合约地址：
2rJNSTVGKzVKEwmAHdXPxhEGAEseztqwVENh7KyVDcUD84pb6nWwYeyM1TwNCZ2jXioc6VypGWsTjFU2vV2XASYs

```
var _addr = /* var of type address here */ ;
var testContract = web3.sero.contract([{"constant":true,"inputs":[],"name":"addr","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_addr","type":"address"}],"name":"setAdderss","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"_addr","type":"address"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]);
var test = testContract.new(
   _addr,
   {
     from: web3.sero.accounts[0], 
     data: '0x608060405234801561001057600080fd5b50604051602080610194833981016040525160008054600160a060020a03909216600160a060020a0319909216919091179055610142806100526000396000f30060806040526004361061004b5763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663767800de81146100505780639189c8fc1461008e575b600080fd5b34801561005c57600080fd5b506100656100be565b6040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f35b34801561009a57600080fd5b506100bc73ffffffffffffffffffffffffffffffffffffffff600435166100da565b005b60005473ffffffffffffffffffffffffffffffffffffffff1681565b6000805473ffffffffffffffffffffffffffffffffffffffff191673ffffffffffffffffffffffffffffffffffffffff929092169190911790555600a165627a7a7230582094a707114aae87be2f5879784d11ff2da2c6fd876bce723661b5b6ad8dfc9e4d0029', 
     gas: '4700000'
   }, function (e, contract){
    console.log(e, contract);
    if (typeof contract.address !== 'undefined') {
         console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);
    }
 })
```

**Comment by mianhuatan** [comment]
好的，抱歉我搞错了我之前部署的时候参数既有主收款码，又有智能合约的地址:
` constructor(address[] addrs, address _serviceAddr) public {
 ...
}`
address[] addrs存放了一些主收款码，address _serviceAddr传入的是另一个合约的地址

部署时发现构造函数的参数不支持 类似address[] 等list结构，我给拉代码下来本地改了改将输入的list参数转成json格式,
然后再部署又会报错：
{messageId: 15, method: "estimateGas", data: "0x0", error: "gas required exceeds allowance or always failing transaction"}
我以为是gas计算的不对，手动设置了gas，交易成功，但是最后部署是失败的

现在看来好像是address 类型 不支持智能合约地址？那智能合约地址要怎么传参？

**Comment by uhexio** [comment]
对的。 estimateGas估算Gas失败，说明合约会执行失败。

目前skit不支持合约地址，因为SERO的接口都需要传入 PKr格式的地址.  使用下面方法可以转换生成, SKit后面会适配地址。

```
async convertAddress(address:string){
	// is contract address
	let hexStr = bs58.decode(address).toString("hex");
	const rightZeroStr = "0000000000000000000000000000000000000000000000000000000000000000";
	const hex = "0x"+hexStr + rightZeroStr;
	
	return bs58.encode(this.hexToBytes(hex))

},

hexToBytes(hex:string) {
	hex = hex.replace(/^0x/i, '');
	for (var bytes = [], c = 0; c < hex.length; c += 2)
	    bytes.push(parseInt(hex.substr(c, 2), 16));
	return bytes;
}
```

**Comment by uhexio** [comment]
Skit already updated and supports address and address [] .

Solidity Example: 

```
pragma solidity ^0.6.6;

pragma experimental ABIEncoderV2;

contract test{
    address public addr;

    address[] public addrs;
    
    constructor(address a1, address[] memory a2) public {
        addr = a1;
        addrs = a2;
    }

}
```

**Comment by mianhuatan** [comment]
非常感谢，已经成功部署合约
